### ISSUE TITLE
Chromecast disconnecting & stopping video

### ISSUE THREAD

**Issue by se-bastiaan** [ConnectSDK/Connect-SDK-Android-Google-Cast#9]
When I play a video and I lock my device, the video stops playing on the Chromecast when art decides to suspend all threads. This results in a 'onServiceRemoved: Chromecast' and that in its place stops the playback of the video on my Chromecast.

I've already tried to acquire a wakelock and wifilock in the activity that contains the controls. But that doesn't work. Any ideas?

It might be good to know that I do not have any lockscreen or notification controls yet.

**Comment by se-bastiaan** [comment]
I noticed that the CastDiscoveryProvider does not use the onRouteRemoved but that it rescans every time. Why? the passive discovery mode that is built into the MediaRouter should be efficient enough, manually forcing a scan is probably worse.

**Comment by khk624** [comment]
I cannot reproduce this issue, my test phone is LG Gpro 1 (lollipop), and using connectsdk 1.4.4. Does it happen 100%?

We've not used onRouteRemoved because sometimes onRouteRemoved had been invoked even if the device was still connected, so that we've changed that to passive discovery mode. Also, it made keep consistency with other discovery provider as well.

**Comment by oleksii-frolov** [comment]
I also tested ConnectSDK 1.4.3 and 1.4.4 on Android 5.1 and didn't reproduce this issue.

**Comment by casolorz** [comment]
This sounds very similar to my issue https://github.com/ConnectSDK/Connect-SDK-Android/issues/254

**Comment by se-bastiaan** [comment]
@mntgoat It looks the same, yes. I saw the same behaviour. But only when I lock my devices.

I forgot to post that using onRouteRemoved worked for me. It just looks like it can't detect it anymore when locked and the Chromecast lib ignores that.

**Comment by casolorz** [comment]
@se-bastiaan yeah mine is also with a locked screen. Either if I press the power button myself or if I let the phone lock itself eventually.

**Comment by se-bastiaan** [comment]
@mntgoat Then it's exactly the same issue. How is your server built? I use AndroidAsync.

**Comment by casolorz** [comment]
@se-bastiaan I should have used AndroidAsync but I already had a NanoHTTPd server from another app and just reused it. Maybe one day I'll switch.

**Comment by se-bastiaan** [comment]
@mntgoat Then it's not the server.

**Comment by casolorz** [comment]
No it definitely isn't. My other app using the CastCompanionLibrary and it happens to have the exact same functionality (serving local files to the chromecast) with the exact same server and it can stream the exact same file just fine.

**Comment by casolorz** [comment]
Also today's test of the special branch without the route remove stuff worked.

**Comment by khk624** [comment]
@se-bastiaan I've created a test branch for this issue (https://github.com/ConnectSDK/Connect-SDK-Android-Google-Cast/tree/discovery_with_onrouteremoved) 

Our team needs to discuss about this first, and we will let you know.

**Comment by casolorz** [comment]
FYI @khk624 the CastCompanionLibrary doesn't have this issue so maybe you guys can look at what it does in this situation. I'm using CCL 1.4, haven't tested 2.0.

**Comment by khk624** [comment]
@mntgoat We've missed this stuff(Lock Screen in https://developers.google.com/cast/docs/android_sender). I think this caused the issue. I will update the new result after test.

**Comment by casolorz** [comment]
Are you talking about this:

```
mAudioManager.requestAudioFocus(null, AudioManager.STREAM_MUSIC,
                AudioManager.AUDIOFOCUS_GAIN_TRANSIENT_MAY_DUCK);
```

because I do that in my code already and I also have an ongoing notification and a wake lock (partial) and a wifi lock (high perf).

**Comment by khk624** [comment]
@mntgoat Yes, I tried but it's not working so far. ~~Did you set up the RemoteControlClient also?~~

Never mind it. We may not need this.

**Comment by se-bastiaan** [comment]
@khk624 I already replace the discovery code by the onRouteRemoved myself. ;)

**Comment by casolorz** [comment]
Sorry @khk624 for some reason I missed your message last night or I didn't get a notification. Yes I tried RemoteControlClient also. 

I have had two users test your fix from that branch and they have both reported the issue as fixed so that branch certainly fixes it, I just don't know if it breaks something else.

**Comment by se-bastiaan** [comment]
Since this has been merged.
